# This Dockerfile is used exclusively for github actions workflow to
# build a linux bundle that runs on most linux distros

# Use pypi blessed manuliunux project with glibc 2.17
FROM quay.io/pypa/manylinux2014_x86_64

# get toolchain necessary to build python from source
RUN yum update -y
RUN yum groupinstall -y 'Development Tools'
# Corrected line: Combined all packages into one yum install command
RUN yum install -y wget zlib-devel bzip2 bzip2-devel \
    readline-devel sqlite sqlite-devel openssl-devel \
    tk-devel libffi-devel xz-devel coreutils

WORKDIR /root

# build python from source with required flag as as pyinstaller needs it
RUN wget https://www.python.org/ftp/python/3.9.13/Python-3.9.13.tar.xz
RUN tar -xf Python-3.9.13.tar.xz
WORKDIR /root/Python-3.9.13
RUN ./configure --prefix=/usr/local --with-system-ffi --enable-shared
RUN make
RUN make altinstall
RUN export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH



WORKDIR /root/config-assessment-tool
COPY backend ./backend
COPY input ./input
COPY VERSION .
COPY Pipfile .
COPY Pipfile.lock .

RUN BUNDLE_VERSION=`cat VERSION`

RUN pipx install pipenv
RUN pipx install pyinstaller
RUN export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH; python3.9 -m pip install --upgrade pip
RUN pipenv requirements --dev > requirements.txt
RUN export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH; pip install -r requirements.txt
RUN export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH; pyinstaller --distpath=./dist/appdynamics backend/config-assessment-tool.spec

WORKDIR /root

# MODIFIED: Define OS and Architecture dynamically AND tar up the bundle in a single RUN instruction
RUN OS_ID=$(grep '^ID=' /etc/os-release | cut -d'=' -f2 | tr -d '"' | tr '[:lower:]' '[:upper:]') && \
    ARCH=$(uname -m) && \
    echo "Detected OS: $OS_ID, Architecture: $ARCH" && \
    ls -altrh && \
    tar -zcvf /root/config-assessment-tool/dist/config-assessment-tool-linux-$(cat config-assessment-tool/VERSION)-${OS_ID}-${ARCH}.tgz -C /root/config-assessment-tool/dist/appdynamics . && \
    ls -altrh /root/config-assessment-tool/dist/appdynamics