name: Create Platform specific bundles
on:
  release:
    types: [ published ]

jobs:

  build-linux:
   name: build linux binary
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Install dependencies
       run: |
         cd backend
         # build image which builds the bundle for glibc 2.15+
         docker build --file Dockerfile-bundle --tag config-assessment-tool-linux .
         # run image and copy the bundle to host runner
         docker run --rm -it -v $(pwd):/app config-assessment-tool-linux
         docker cp $(docker create --name temp_image config-linux-bundle:v0):/root/config-assessment-tool/dist/appdynamics/config-assessment-tool-linux-v1.4.20.tgz ./ && docker rm temp_image
     - name: Release the bundle for linux
       uses: softprops/action-gh-release@v1
       if: startsWith(github.ref, 'refs/tags/')
       with:
         files: ./appdynamics/*.tgz
         token: ${{ secrets.WORKFLOW_TOKEN }}
