name: Create Platform specific bundles
on:
  release:
    types: [ published ]

jobs:

  build-linux:
   name: build linux binary
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Install dependencies
       run: |
         cd backend
         # build image which builds the bundle for glibc 2.15+
         docker build --file Dockerfile-github-workflow-bundle --tag config-assessment-tool-linux .
         # copy bundle out of built image
         tarball_path=$(docker run --rm config-assessment-tool-linux:latest  ls /root/config-assessment-tool/dist/appdynamics/config-assessment-tool-linux-*.tar.gz)
         docker cp $(docker create --name temp_image config-assessment-tool-linux:latest):$tarball_path ./ && docker rm temp_image
         cd
         ls -altr
         find . -name *.tgz
     - name: Release the bundle for linux
       uses: softprops/action-gh-release@v1
       if: startsWith(github.ref, 'refs/tags/')
       with:
         files: ./appdynamics/*.tgz
         token: ${{ secrets.WORKFLOW_TOKEN }}
     - name: Keep workflow artifact within the current workflow namespace
       uses: actions/upload-artifact@v3
       with:
        name: config-assessment-tool-linux.tgz
        path: ./config-assessment-tool-linux-*.tgz
        if-no-files-found: warn